version: '2.1'
services:
  riotly-server:
    container_name: riotly-server
    build: ./server/
    command: npm start
    volumes:
      - './server:/usr/src/app'
      - './server/package.json:/usr/src/package.json'
    ports:
      - "8000:8000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    links:
      - riotly-mongo
  riotly-mongo:
    image: "mongo:3.4"
    ports:
      - "27017:27017"
  riotly-client:
    container_name: riotly-client
    build: ./client/
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
    depends_on:
      riotly-server:
        condition: service_started
    links:
      - riotly-server